# .graphclientrc.yml
sources:
  - name: txs-ethereum
    handler:
      graphql:
        endpoint: https://rail-squid.squids.live/squid-railgun-ethereum-v2/graphql
documents:
  - ./railgun-txids-query.graphql
